chore(engine): add debug logs to improve job acquisition job execution logging
operaton/operaton pull request #367
Opened 2024-12-22 10:47 UTC by hauptmedia

* add test cases for the job-acquisition and job-execution logs

related https://github.com/camunda/camunda-bpm-platform/issues/2666

Backported commit 824b35f3f2 from the camunda-bpm-platform repository.
Original author: Palanisamy, Prakash <prakash.palanisamy@fmr.com>

2025-01-07 08:10 UTC, javahippie requested changes

2025-01-07 08:10 UTC, javahippie commented on engine-spring/core/src/main/java/org/operaton/bpm/engine/spring/components/jobexecutor/SpringJobExecutor.java
> +			if (taskExecutor instanceof ThreadPoolTaskExecutor) {
We have refactored "instanceof" checks to use the "new" style with direct assignment, I'd prefer if we did this in the backports directly, to not import this old style into our repo again

2025-02-05 16:43 UTC, javahippie commented on engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/RuntimeContainerJobExecutor.java
> +    if (executorService instanceof JmxManagedThreadPool) {
Same here with the newer instanceof style, sorry for not catching it in the first review

2025-02-07 16:06 UTC, kthoms approved these changes

2025-02-07 16:06 UTC, merged