fix(asyncInstanceModification): respect ancestor during startBefore/after cmd execution (#4829)
operaton/operaton pull request #369
Opened 2024-12-22 11:14 UTC by hauptmedia

related to camunda/camunda-bpm-platform#4507

Backported commit 7bf5c46119 from the camunda-bpm-platform repository.
Original author: Helene <21290204+PHWaechtler@users.noreply.github.com>

2025-01-07 08:11 UTC, javahippie commented on engine/src/main/java/org/operaton/bpm/engine/impl/json/ModificationCmdJsonConverter.java
> +    if (command instanceof ActivityAfterInstantiationCmd) {
We have refactored "instanceof" checks to use the "new" style with direct assignment, I'd prefer if we did this in the backports directly, to not import this old style into our repo again

2025-01-07 08:12 UTC, javahippie requested changes
Please take a look at the `instanceof` checks

2025-02-07 16:04 UTC, kthoms commented
I have fixed the findings and cleaned up the PR

2025-02-11 22:22 UTC, javahippie approved these changes

2025-02-11 22:22 UTC, merged