tests(starter): add tests for oauth2 and identity  (fixes #175)
operaton/operaton pull request #371
Opened 2024-12-22 11:49 UTC by hauptmedia

related to https://github.com/camunda/camunda-bpm-platform/issues/4453

Backported commit 2d02d61410 from the camunda-bpm-platform repository.
Original author: Joaquín <joaquin.felici@camunda.com>

2025-01-07 08:13 UTC, javahippie approved these changes

2025-01-07 22:10 UTC, kthoms commented
@hauptmedia Could you rebase and resolve the conflict, please?

2025-01-09 09:06 UTC, javahippie requested changes
Rebase due to conflicts needed

2025-01-09 13:27 UTC, hauptmedia commented
will fix it, converted it to draft for the time being

2025-01-15 14:00 UTC, hauptmedia commented
@javahippie I resolved the conflicts

2025-01-23 10:22 UTC, merged